### ISSUE TITLE
Missing variants

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#22]
- [ ] On all LTM4644s INTVCC supply and ground are tied together with 0R jumpers

- [ ] SDIO_DETECT R452 or R454 one of them should be mounted

**Comment by tprzywoz** [comment]
Fixed variants in CDR_WR_oscillators. 
LTM4644 MODE default connected to GND (INTVCC disconnected).
SDIO_DETECT default pullup.
