### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#33]
The most probably, USB is in host configuration (as in ZCU111) then:

- [ ] Vbus resistorR614 should be 10k

- [ ] C818 should be more than 120uF

**Comment by tprzywoz** [comment]
I assumed that you meant 10k and I changed that.
Capacitors copied from AFCZ: 3 x 47uF.

**Comment by filipswit** [comment]
Of course 10k.
