### ISSUE TITLE
Power supply control and I2C mux reset during MMC reset

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#44]
As in AFC and AFCZ, add MCP23016 for power sequecing.

**Comment by tprzywoz** [comment]
Added TCA9539 like in AFCZ. I reduced enable lines to 18 to avoid second IO expander. Consequences:

- AMS_CLK_VCC3V3 LDO enable connected to VIN (P3V5). 
- P2V5 / DAC_AVTT enable connected to VIN (P5V0).
- One common enable signal for DAC_AVCC / DAC_AVCCAUX / ADC_AVCC (Xilinx DS926: can be powered at any time and have no power-up sequencing requirements.)
