### ISSUE TITLE
RTM I2C Bus Isolation an Pull-Ups

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#50]
According to mTCA 4.1 specification RTM I2C bus should be separated by bidirectional buffer powered from P3V3_MP (REQ 3-7).

RTM I2C pull-ups should be present only on RTM module, according to Figure 3-1.

https://github.com/elhep/AFCZ/issues/20

**Comment by tprzywoz** [comment]
Copied AFCZ solution.
