### ISSUE TITLE
L2 L25 ferrite beads current rating

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#55]
Current flow is over component current rating (2x2A), while estimated current is 5,3A.

**Comment by tprzywoz** [comment]
![image](https://user-images.githubusercontent.com/30114557/117676491-e2f38200-b1ad-11eb-9472-c7511f232f25.png)

5,3A is current of P1V2 + MGTAVTTF. MGTAVTTF estimated current is 0,4A

**Comment by filipswit** [comment]
ok, sorry.
