### ISSUE TITLE
IC7 improper value phaze boost capacitor

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#56]
C287 should be 47pF instead of 47nF

![image](https://user-images.githubusercontent.com/24258965/117583951-5b086c00-b10a-11eb-8bfb-7f2bcd74214d.png)

**Comment by tprzywoz** [comment]
I copied the value from ZCU111 (U100). I suggest keep 47nF, we can easily change it later.

**Comment by filipswit** [comment]
ok
