### ISSUE TITLE
Swapped polatity

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#60]
Polarity is swapped on:

- SS_USB
![image](https://user-images.githubusercontent.com/24258965/117584360-c5221080-b10c-11eb-8d77-db8b511efdc2.png)

- GTY_REF_130
![image](https://user-images.githubusercontent.com/24258965/117584369-cc491e80-b10c-11eb-9e6b-9d81f14f6328.png)

- GTY_REF_129
![image](https://user-images.githubusercontent.com/24258965/117584372-d2d79600-b10c-11eb-9cd3-ea7e88739549.png)

- GTY_REF_128
![image](https://user-images.githubusercontent.com/24258965/117584375-d9660d80-b10c-11eb-8440-9ed4f779ec52.png)

- ARTIX_FPGA_GTP_CLK

![image](https://user-images.githubusercontent.com/24258965/117584393-f995cc80-b10c-11eb-9edf-fc6de33435c7.png)

**Comment by tprzywoz** [comment]
Fixed
