### ISSUE TITLE
Missing pull-ups

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#61]
ARTIX_CFG_ 
- PROG_B 
- INIT_B 

should have an external ≤ 4.7 kΩ pull-up resistors to VCCO_0.

**Comment by tprzywoz** [comment]
Added 4.7 kΩ pull-up resistors
![image](https://user-images.githubusercontent.com/30114557/117799938-f0af1300-b252-11eb-8454-e1d88563464e.png)
