### ISSUE TITLE
LMX2594 charge pump filter

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#63]
On dev kit values of resistors are 0R and 18R instead of 2R and 2R
![image](https://user-images.githubusercontent.com/24258965/117584521-c9026280-b10d-11eb-9cb0-1765c3ad05b2.png)
![image](https://user-images.githubusercontent.com/24258965/117584527-cb64bc80-b10d-11eb-81a0-86e2080c6a4f.png)

**Comment by tprzywoz** [comment]
Changed (also 0603 changed to 0402)
