### ISSUE TITLE
Lack of recommended capacitors

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#65]
On Artix power supply rails, Xilinx recommends some additional capacitors, so it would be good to add:

- VCCINT
100uF

- VCCBRAMF
47uF

- VCCAUXF
47uF and 2x4.7uF

- Each VCCO_x
47uF and 4.7uF

- Each MGT supply
4.7uF

**Comment by tprzywoz** [comment]
The design was copied from Sayma_RTM so it should work. But I added all recommended capacitors except 47uF for VCCOx.
