### ISSUE TITLE
schematic details

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#67]
- [ ] missing logo
![image](https://user-images.githubusercontent.com/24258965/118410603-89e58b80-b690-11eb-8d5c-5b968b5929b5.png)

- [ ] table not updated
![image](https://user-images.githubusercontent.com/24258965/118410614-9f5ab580-b690-11eb-86bf-75603fb55aee.png)

- [ ] out of sheet object
![image](https://user-images.githubusercontent.com/24258965/118412289-7b4fa200-b699-11eb-8206-d907b2ac604e.png)

**Comment by tprzywoz** [comment]
Done

**Comment by filipswit** [comment]
- [ ] missing file
![image](https://user-images.githubusercontent.com/24258965/119231359-cac22200-bb20-11eb-8ff3-cf7068b96b7d.png)

**Comment by filipswit** [comment]
- [ ]  Missing files on sheet SoC_FPGA_64_65_66_DDR4.SchDoc
![image](https://user-images.githubusercontent.com/24258965/120069884-766ef300-c088-11eb-801f-9aca24faaaf5.png)
