### ISSUE TITLE
multiple net names

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#69]
Is there any reason why there are multiple net names?
![image](https://user-images.githubusercontent.com/24258965/118412208-ff555a00-b698-11eb-8d76-dd949ad2dc8b.png)

It's the same with: DAC_AVCCAUX, ADC_AVCC, MGRTAVCC

**Comment by tprzywoz** [comment]
Deleted redundant "BUS" names. Should be removed together with current sense resistors which were between power net and _bus net.
