### ISSUE TITLE
Unconnected via

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#73]
- [ ]  close to IC36 via is not connected to power plane, move plane border to connect it
![image](https://user-images.githubusercontent.com/24258965/119234749-b89bb000-bb2f-11eb-950a-a30b9b314d32.png)

- [ ] C651
![image](https://user-images.githubusercontent.com/24258965/119270831-f1ef2100-bbfe-11eb-8c6f-08b2b31cf6db.png)

**Comment by tprzywoz** [comment]
Fixed

![image](https://user-images.githubusercontent.com/30114557/119341970-b868f500-bc94-11eb-887b-793c54a93165.png)

![image](https://user-images.githubusercontent.com/30114557/119342094-db93a480-bc94-11eb-801f-3c962511bd4a.png)
