### ISSUE TITLE
tie polygon P2V5

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#78]
Tie polygon P2V5 on L16 with more vias, now it's tied with one via. Turn on "remove dead copper" on it, there is floating part.

**Comment by tprzywoz** [comment]
Removed dead copper, added 4 vias:
![image](https://user-images.githubusercontent.com/30114557/119988641-9a6a0000-bfc6-11eb-9637-a16214904582.png)
