### ISSUE TITLE
DESY recommendation class D1.4 for RTM connector

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#8]
According to changes in AFCv4 and AFCZ please make connector compatible with D1.4 recomendation https://github.com/elhep/AFCZ/issues/29

**Comment by tprzywoz** [comment]
@gkasprow I assume RTM_4SFP_3QSFP will also be compatible with D1.4.

**Comment by gkasprow** [comment]
what features of RTM_4SFP_3QSFP  are not compatible with D1.4 ?

**Comment by tprzywoz** [comment]
CLKA clock https://github.com/elhep/RTM_4SFP_3QSFP/issues/4

**Comment by tprzywoz** [comment]
I made connector compatible with D1.4 with one exception: there is no free SRCC/MRCC IO for CC IO's, so they are connected to ''normal" Artix pins (bank 2.5V for LVDS).
