### ISSUE TITLE
components to close to each other

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#83]
- [ ] IC63 is to close to C936
- [ ] This selector will be hard to change with mounted radiator
![image](https://user-images.githubusercontent.com/24258965/119271691-db4ac900-bc02-11eb-8b89-3a7d58093eb3.png)

**Comment by filipswit** [comment]
- [ ] C373 C372, can be moved to the left, to wouldn't overlap of IC23 courtyard
![image](https://user-images.githubusercontent.com/24258965/120069409-30189480-c086-11eb-8fe3-9c024855613f.png)

**Comment by filipswit** [comment]
- [ ] This selector will be hard to change with mounted radiator

![image](https://user-images.githubusercontent.com/24258965/120079223-3a04bc80-c0b3-11eb-8355-269e6dc8e52a.png)

**Comment by tprzywoz** [comment]
All done. The first selector moved to BTM:
![image](https://user-images.githubusercontent.com/30114557/121207486-9d43db00-c879-11eb-9466-7c44edb5b924.png)
