### ISSUE TITLE
General RAM issue

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#84]
Mostly one byte is routed on few layers. It should be on one. 

UG583:
``DQ and DQS signals in the same byte group should be routed in the same layer from
UltraScale device to DRAM/DIMM, except in the breakout areas. Include the data mask
(DM) in the byte group as applicable.``

**Comment by tprzywoz** [comment]
As current design has passed all RAM simulation tests, I think that it's not worth changing the layout.

**Comment by filipswit** [comment]
In general I dislike it. But since Altium count delays and simulation passes it may be right.
