### ISSUE TITLE
Swapped polarity on RTM connector

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#9]
![image](https://user-images.githubusercontent.com/24258965/97225125-852fb780-17d2-11eb-942e-1240436a3a9c.png)

**Comment by gkasprow** [comment]
LEt's call all RTM LVDS line just LVDSxx as it is now in Sayma boards

**Comment by tprzywoz** [comment]
Fixed. I renamed IOs line as in AFC board.
![image](https://user-images.githubusercontent.com/30114557/97473139-f09c9500-194a-11eb-857c-a2300435e126.png)
