### ISSUE TITLE
unmasked vias

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#90]
- [ ] 

![image](https://user-images.githubusercontent.com/24258965/120076830-d6c15d00-c0a7-11eb-9414-3cb8bee1a97c.png)

- [ ] 
![image](https://user-images.githubusercontent.com/24258965/120078427-d3ca6a80-c0af-11eb-9c83-5b29fe83b6f6.png)

**Comment by tprzywoz** [comment]
done
