### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/RFSOC-AMC#91]
- [ ] Overlapping designator
![image](https://user-images.githubusercontent.com/24258965/120077597-72080180-c0ab-11eb-887c-05b56a98608f.png)

- [ ] Add description to DAC_AVCC test point
- [ ] Add description to FPGA_I2C test point
- [ ] Add description to MMC_I2C test point
- [ ] Add description to headers: JTAG, I2C, Ethernet
- [ ] Add board description
- [ ] rotate label L33
- [ ] rotate label IC35
- [ ] J3 label out of the board

**Comment by tprzywoz** [comment]
Done. Added description for both RFSoC and Artix I2C.

**Comment by tprzywoz** [comment]
Added variants description:
![image](https://user-images.githubusercontent.com/30114557/120201425-b8816b80-c225-11eb-9c88-da01e5e461a1.png)
